Repository calyxir/calyx, pull requests merged in 2021-10, with the labels that each got.

#701 [docs] Documentation for CIRCT round-trip.
  docs/SUMMARY.md
  docs/fud/circt.md
  tests/backend/mlir/simple.expect
  tests/backend/mlir/simple.futil
Labels: Comp: Calyx, Comp: Fud, Comp: CIRCT

#706 [CIRCT] Add attributes for groups.
  calyx/src/ir/structure.rs
  src/backend/mlir.rs
  tests/backend/mlir/attributes.expect
Labels: Comp: CIRCT

#700 Fixed point operators
  interp/src/environment.rs
  interp/src/macros.rs
  interp/src/primitives/combinational.rs
  interp/src/primitives/stateful.rs
  interp/src/values.rs
Labels: Comp: Interpreter

#707 [CIRCT] Add changes for symbolic instance names.
  src/backend/mlir.rs
  tests/backend/mlir/attributes.expect
  tests/backend/mlir/no-guards.expect
  tests/backend/mlir/simple.expect
  tests/backend/mlir/with-guards.expect
Labels: Comp: CIRCT

#761 [Passes] Reset all things.
  calyx/src/passes/reset_insertion.rs
  examples/futil/dot-product.expect
  examples/futil/multi-component.expect
  examples/futil/pass-in-register.expect
  examples/futil/simple.expect
  examples/futil/vectorized-add.expect
  tests/passes/regressions/group-multi-drive.expect
Labels: Comp: Calyx

#753 [library] Use reset in `sqrt` to represent running state.
  primitives/math.futil
  primitives/math.sv
Labels: Comp: Library

#765 Fix unmatched golden output issue with sqrt.
  primitives/math.sv
Labels: Comp: Library
